language: php

php:
  - 7.0
services:
  - mysql
before_install:
- mysql -e 'CREATE DATABASE scotchbox;'
- composer global require --dev sebastian/phpcpd
- sudo apt-get update
#- sudo apt-get install php7.0-xml
- composer update
- cp .env.example .env
- php artisan key:generate
- php artisan migrate --seed
test:
  adapter: mysql2
  database: scotchbox
  username: travis
  encoding: utf8
before_script:
  - php phpcpd ../../app/Http/Controllers/BooksController.php
